// Composition idea: star cloud formation:
// Initial sound cloud in 0 order, then individual pan areas form gradually in time becoming different from each other and the initial undiferentiated sound soup of all pan locations.
// Architecture: pan locations array. Dedicated synth instance sequence for each location, differing in time from being the same to other instances.
// Different approach than movement: sequencies remain on the same location, and the do not have static randomness patterns but evolve in a continuous difference with initail index 0, from each other.
// Requirements: movement synth for every location, or simply non local sound to local sound gradient.
// Eg. When in no differentiatiom and order 0 the magnitude for each location is the same, thus everywhere the same interval. When spherical harminics are applied locations start to diferentiate in pitch according to the modulation of magnitude, higher magnitudes meaning higher pitch and lower, lower pitch.